receivers:
- name: alert_channel
  webhook_configs:
    - url: 'http://prometheus-msteams:2000/alert_channel'
      send_resolved: true
route:
    group_by: ['...']
    group_interval: 5m
    group_wait: 30s
    receiver: alert_channel
    repeat_interval: 3h
