## docker-compose.yml ##

version: '3'

services:

  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml
      - ./prometheus_data:/prometheus
    ports:
      - "9090:9090"

  alertmanager:
    container_name: alertmanager
    hostname: alertmanager
    image: prom/alertmanager
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"

  prometheus-msteams:
    container_name: prometheus-msteams
    hostname: prometheus-msteams
    image: docker.io/bzon/prometheus-msteams:v1.1.4
    volumes:
      - ./msteams_config.yaml:/tmp/config.yaml
      - ./card.tmpl:/tmp/card.tmpl
    environment:
      - CONFIG_FILE=/tmp/config.yaml
      - TEMPLATE_FILE=/tmp/card.tmpl
    ports:
      - "2000:2000"