## docker-compose.yml ##

version: '3'

volumes:
  prometheus_data: {}
  grafana_data: {}

services:

  alertmanager:
    container_name: alertmanager
    hostname: alertmanager
    image: prom/alertmanager
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    ports:
      - "9093:9093"

  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    links:
      - alertmanager:alertmanager
    ports:
      - "9090:9090"

  grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana
    volumes:
      - ./grafana_datasources.yml:/etc/grafana/provisioning/datasources/all.yaml
      - ./grafana_config.ini:/etc/grafana/config.ini
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"

  prometheus-msteams:
    container_name: prometheus-msteams
    hostname: prometheus-msteams
    image: docker.io/bzon/prometheus-msteams:v1.1.4
    volumes:
      - ./msteams_config.yaml:/tmp/config.yaml
      - ./card.tmpl:/tmp/card.tmpl
    environment:
      - CONFIG_FILE=/tmp/config.yaml
      - TEMPLATE_FILE=/tmp/card.tmpl
    ports:
      - "2000:2000"